
version: "3"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:2.5.6
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - config_heimdall:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

volumes:
  config_heimdall: