version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:2023.8"
    volumes:
      - config_homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  emqx:
    image: emqx/emqx:5.1.5
    container_name: emqx
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    ports:
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083 
    volumes:
       - data_emqx:/opt/emqx/data
       - config_emqx:/opt/emqx/etc
       - log_emqx:/opt/emqx/log

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.32.2
    restart: unless-stopped
    volumes:
      - data_zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    environment:
      - TZ=Europe/Berlin
    devices:
      - /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20221031090404-if00:/dev/ttyACM0

  vscode:
    container_name: vscode
    image: codercom/code-server:4.16.1
    volumes:
      - config_homeassistant:/home/coder/project
    ports:
      - "8443:8443"
    command: code-server --port 8443 --disable-telemetry /home/coder/project
    restart: unless-stopped

volumes:
  config_homeassistant:
  config_emqx:
  data_emqx:
  log_emqx:
  data_zigbee2mqtt: