version: '3'

services:
  influxdb:
    image: influxdb:2.7.1
    container_name: influxdb
    ports:
      - "8086:8086"
    env_file:
      - 'env.influxdb'
    volumes:
      - data_influxdb:/var/lib/influxdb2 

  telegraf:
    image: telegraf:1.27.3
    container_name: telegraf
    env_file:
      - 'env.telegraf'
    volumes:
      - /:/hostfs:ro
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

  grafana:
    image: grafana/grafana:7.3.7     
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - 'env.grafana'
    user: root
    volumes:
      - data_grafana:/var/lib/grafana

volumes:
  data_influxdb:
  data_grafana: