version: '3.4'

services:
  influxdb:
    image: influxdb:2.7.1
    container_name: influxdb
    ports:
      - "8086:8086"
    env_file:
      - 'env.influxdb'
    volumes:
      - data_influxdb:/var/lib/influxdb2
      - config_influxdb:/etc/influxdb2/
    restart: unless-stopped

  telegraf:
    image: telegraf:1.27.3
    container_name: telegraf
    hostname: "domo-01"
    user: telegraf:997
    env_file:
      - 'env.telegraf'
    volumes:
      - /:/hostfs:ro
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  grafana:
    image: grafana/grafana:9.5.8   
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - 'env.grafana'
    user: '0'
    volumes:
      - data_grafana:/var/lib/grafana
    restart: unless-stopped

volumes:
  config_influxdb:
  data_influxdb:
  data_grafana: